name: astrologia
favicon: null
layout_spectrum: 0.6930288586299866
typography_spectrum: 0.291245544096455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.32912088884040713
  lightness: 0.056425526505336165
  saturation: 0.19428153824992478
  rhythmicContrast: 0.7920224850531667
purpose: []
