typography_spectrum: 0.291245544096455
color:
  brandColors:
    - '#232175'
    - '#ffffff'
    - '#025fac'
    - '#59c4f0'
    - '#c2bfd5'
  brandStrength: 0.32912088884040713
  lightness: 0.056425526505336165
  saturation: 0.19428153824992478
  rhythmicContrast: 0.7920224850531667
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6930288586299866
analytics:
  google: null
  facebook: null
  twitter: null
name: astrologia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
